// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function TwitterCore(arg1:core.TwitterDownload):Promise<{[key: string]: any}>;
