// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TwitterCore(arg1) {
  return window['go']['apps']['App']['TwitterCore'](arg1);
}
